### ISSUE TITLE
OPEN packet not returned by server

### ISSUE THREAD

**Issue by jjarur** [cryptomkt/cryptomkt-python#10]
Por algun motivo recibo el error "OPEN Packet not returned by server"
El código es simple, pero ¿tienen alguna idea del motivo?.

from cryptomarket.exchange.client import Client
import json

api_key = '######'
api_secret= '#######'
client = Client(api_key, api_secret)

socket = client.get_socket()

**Comment by etiennecelery** [comment]
+1

**Comment by TGRaydas** [comment]
Mismo issue... no hay solución aun?

Gracias!

**Comment by etiennecelery** [comment]
Cuánto pagarías por la solución?

**Comment by TGRaydas** [comment]
Nada, migre a JS y listo.

**Comment by Insmael** [comment]
La nueva versión del sdk cambió a una api más actualizada, por lo que el issue ya no es un problema, gracias por el apoyo.
