### ISSUE TITLE
No name 'exchange' in module 'cryptomarket'

### ISSUE THREAD

**Issue by carambolo-tocololo** [cryptomkt/cryptomkt-python#11]
Hola!!

Soy nuevo en la comunidad y esto recién aprendiendo a programar en python.
Seguí las instrucciones y me aparecen dos problemas en la Consola:

No name 'exchange' in module 'cryptomarket'
Unable to import 'cryptomarket.exchange.client'

Alguna idea de qué puede estar pasando y cómo solucionarlo?
Muchas gracias!

**Comment by tvallotton** [comment]
Los docs parecen estar desactualizados. Mejor usa `from cryptomkt import Client`.

**Comment by Insmael** [comment]
Hola,
El problema parece tener que ver con la instalación del módulo. Probé una instalación del antiguo sdk como clon del repo, y con un ```pip install .``` reconoció los módulos, lo que me lleva a pensar que tiene que ver con la instalación.

En cualquier caso, el problema que tienes es con el sdk antiguo, por lo que voy a cerrar el issue. Si sigues con problemas con la nueva versión del sdk, avísanos.
