### ISSUE TITLE
client.get_executed_orders raises InvalidRequestError: APIError(id=): invalid_request

### ISSUE THREAD

**Issue by tomyo** [cryptomkt/cryptomkt-python#2]
Hola!
Me pasa algo extraño con esta función y el mercado en ARS.
Cuando ejecuto client.get_executed_orders('XLMARS'), obtengo  `InvalidRequestError: APIError(id=): invalid_request`, lo mismo pasa con cualquier par de market terminado en `ARS`, pero devuelve exitosamente el resultado de cualquier combinación con CLP.

Alguna sugerencia?

```
..../cryptomarket/exchange/client.pyc in _handle_response(self, response)
     80         """
     81         if not str(response.status_code).startswith('2'):
---> 82             raise build_api_error(response)
     83         return response
```
De paso sugiero que este SDK devuelva mayor detalle del error que devuelve la API, si es posible.

Gracias!

**Comment by rmeruane** [comment]
The issue has been solved
