### ISSUE TITLE
Possible error with pip install

### ISSUE THREAD

**Issue by Austral-IV** [cryptomkt/cryptomkt-python#27]
I followed the install instructions, but it seems the "datacasses" folder does not download properly. 
![image](https://github.com/cryptomkt/cryptomkt-python/assets/69649197/0133d728-94b9-46e9-a4de-9394f65e9dc5)

I ended up just downloading from github.

**Comment by ppbustamante** [comment]
Hi @Austral-IV. There was a problem with the packaging. It has been fixed in version 3.2.4. Thank you very much for the warning.
