### ISSUE TITLE
Duda con Client.get_prices_history

### ISSUE THREAD

**Issue by Quiece** [cryptomkt/cryptomkt-python#28]
Estoy intenando plotear los precios del último día/mes, pero lo único que retorna el método get_prices_history es un dict con una lista de un elemento, y siempre del mismo timestamp:

    client.get_prices_history(
        to='CLP',
        source='BTC',
        period='D1',
        sort='ASC'
    )
retorna

    {'BTC': PriceHistory(currency='CLP', history=[PricePoint(timestamp='2021-10-31T00:00:00.000Z', open='50263551', close='50777399', min='49215836', max='51000000')])}

Sin importar los parámetros, history siempre parece tener un solo elemento. Estoy haciendo algo mal?

**Comment by ppbustamante** [comment]
Hola @Quiece. Esa URL tiene el parámetro `limit`, el que por defecto es `1`, por eso solo recibes un elemento.

Acá más información https://api.exchange.cryptomkt.com/#get-prices-history

Saludos
